### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by cgpro** [jpkha/nextjs13-storyblok#4]
When I run a fresh setup, there is still one package missing: storyblok-js-client
Maybe you'll add it.

**Comment by jpkha** [comment]
@cgpro  thank you for raising issue. 
I just tried to run a fresh setup but I did not get any issue. 
The missing dependency should be install automatically because `storyblok-js-client` is known as dependencies in  [@storyblok/js](https://github.com/storyblok/storyblok-js/blob/main/lib/package.json) package.json. 

Could you give me your scenario ? Do you use npm or yarn ?

**Comment by cgpro** [comment]
Ah, I think storyblok CLI was missing on my system. It works without the global cli-package, but I have to install storyblok-js-client independently.
